#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get install nginx -y
sed -i "15i\add_header X-Served-By $HOSTNAME;" /stc/nginx/nginx.conf
sudo service nginx restart
