#!/usr/bin/env bash
# Script to print x10 and change 4 & 8

i=1
while (( i < 11 ))
    do
        if [ $i -eq 4 ]; then
            echo "bad luck"
        elif [ $i -eq 8 ]; then
            echo "good luck"
        else
            echo "Holberton School"
        fi
    (( i++ ))
done
