#!/usr/bin/env bash
# Script to print x10 and change 4, 8 and 17

i=1
while (( i < 21 ))
    do
        case $i in
            4)
                echo $i
                echo "bad luck from China"
            ;;
            9)
                echo $i
                echo "bad luck from Japan"
            ;;
            17)
                echo $i
                echo "bad luck from Italy"
            ;;
            *)
                echo $i
        esac
    (( i++ ))
done
