#!/usr/bin/env bash
# user is a superuser
echo "worker_processes 4;events { worker_connections 1024;}http {server {listen 8080;}}" > /tmp/conf
pkill apache2
sudo -u nginx bash -c "nginx -c /tmp/conf"
